services:
  app_delete:
    build:
      context: .
      dockerfile: Dockerfile
    image: booking-management-app:latest
    container_name: app_delete_booking
    volumes:
      - .:/app
    ports:
      - "5024:5024"
    networks:
      - booking-management-net
    working_dir: /app
    env_file:
     - .env
    command: ["python", "app.py"]
    restart: always

networks:
  booking-management-net:
    driver: bridge
