services:
  app_delete:
    build:
      context: .
      dockerfile: Dockerfile
    image: flight-management-app:latest
    container_name: app_delete_flight
    volumes:
      - .:/app
    ports:
      - "5035:5035"
    networks:
      - flight-management-net
    working_dir: /app
    env_file:
      - .env
    command: ["python", "app.py"]
    restart: always

networks:
  flight-management-net:
    driver: bridge
