version: '3.9'

services:
  app_create:
    build:
      context: . 
    image: booking-management-app:latest 
    volumes:
      - ./create_booking:/app  
    ports:
      - "5021:5021"
    depends_on:
      - db_postgres
    networks:
      - booking-management-net
    command: app.py }

  app_get:
    build:
      context: .
    image: booking-management-app:latest
    volumes:
      - ./get_booking:/app
    ports:
      - "5022:5022"
    depends_on:
      - db_postgres
    networks:
      - booking-management-net
    command: app.py


  app_update:
    build:
      context: .
    image: booking-management-app:latest
    volumes:
      - ./update_booking:/app
    ports:
      - "5023:5023"
    depends_on:
      - db_postgres
    networks:
      - booking-management-net
    command: app.py

  app_delete:
    build:
      context: .
    image: booking-management-app:latest
    volumes:
      - ./delete_booking:/app
    ports:
      - "5024:5024"
    depends_on:
      - db_postgres
    networks:
      - booking-management-net
    command: app.py

  db_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D1str1bu1D4.
      POSTGRES_DB: booking-management-db
    ports:
      - "5433:5432"
    networks:
      - booking-management-net

networks:
  booking-management-net:
    driver: bridge