version: '3.8'

services:
  app_create:
    build:
      context: .
    image: flight-management-app:latest
    volumes:
      - ./create_flight:/app
    ports:
      - "5031:5031"
    depends_on:
      - db_postgres
    networks:
      - flight-management-net
    command: app.py 

  app_get_all:
    build:
      context: .
    image: flight-management-app:latest
    volumes:
      - ./get_flights:/app
    ports:
      - "5032:5032"
    depends_on:
      - db_postgres
    networks:
      - flight-management-net
    command: app.py  

  app_get:
    build:
      context: .
    image: flight-management-app:latest
    volumes:
      - ./get_flight:/app
    ports:
      - "5033:5033"
    depends_on:
      - db_postgres
    networks:
      - flight-management-net
    command: app.py 

  app_update:
    build:
      context: .
    image: flight-management-app:latest
    volumes:
      - ./update_flight:/app
    ports:
      - "5034:5034"
    depends_on:
      - db_postgres
    networks:
      - flight-management-net
    command: app.py  

  app_delete:
    build:
      context: .
    image: flight-management-app:latest
    volumes:
      - ./delete_flight:/app
    ports:
      - "5035:5035"
    depends_on:
      - db_postgres
    networks:
      - flight-management-net
    command: app.py 

  db_postgres:
    image: postgres:13
    container_name: postgres_flights
    restart: always
    environment:
      POSTGRES_DB: flight-management-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D1str1bu1D4.
    ports:
      - "5434:5432"
    networks:
      - flight-management-net
      

networks:
  flight-management-net:
    driver: bridge
