version: '3.8'

services:
  app_create:
    build: .
    ports:
      - "5011:5011"
    depends_on:
      - db
    networks:
      - flights-management-net
    command: python microservices/create_flight.py

  app_get:
    build: .
    ports:
      - "5012:5012"
    depends_on:
      - db
    networks:
      - flights-management-net
    command: python microservices/get_flight.py

  app_update:
    build: .
    ports:
      - "5013:5013"
    depends_on:
      - db
    networks:
      - flights-management-net
    command: python microservices/update_flight.py

  app_delete:
    build: .
    ports:
      - "5014:5014"
    depends_on:
      - db
    networks:
      - flights-management-net
    command: python microservices/delete_flight.py

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flights_management
    ports:
      - "3306:3306"
    networks:
      - flights-management-net

networks:
  flights-management-net:
    driver: bridge
